source 'https://rubygems.org'

gem 'opal', '0.7.2'#,        :github => 'opal/opal'
gem 'opal-jquery', '0.3.0'#, :github => 'opal/opal-jquery'
gem 'opal-rspec', '0.4.3'#,  '0.3.0.beta2'
gem 'opal-browser'#, github: 'opal/opal-browser'
gem 'lissio'# , github: 'meh/lissio'
gem 'opal-irb', '0.7.1' # github: 'fkchang/opal-irb'
gem 'reactive-ruby'
gem 'reactive-router'
gem 'clearwater'
gem 'grand_central'
gem 'middleman'
gem 'middleman-sprockets'#, github: 'middleman/middleman-sprockets'
gem 'middleman-gh-pages'

gem 'haml'
