source 'https://rubygems.org'

gem 'opal', '0.8.1'#,        :github => 'opal/opal'
gem 'opal-jquery', '0.4.1'#, :github => 'opal/opal-jquery'
gem 'opal-rspec', '0.4.3'#,  '0.3.0.beta2'
gem 'opal-browser'#, github: 'opal/opal-browser'
gem 'lissio'# , github: 'meh/lissio'
gem 'opal-irb', '0.8.1' # github: 'fkchang/opal-irb'
gem 'reactrb', '0.8.7'
# gem 'reactive-ruby', '0.7.32'
gem 'reactive-router'
gem 'clearwater'
gem 'grand_central'
gem 'middleman'
gem 'middleman-sprockets', '4.0.0'
gem 'middleman-gh-pages'

gem 'haml'
